SUBJECT: Error in IQAMA_JOB_AHJ_DOT-CARE on AHQ-AI-02
TIME: 2025-04-30 17:19:49
HOST: AHQ-AI-02
SYSTEM: Windows 2019Server
PYTHON: 3.12.8

==================================================

An error occurred in the IQAMA_JOB_AHJ_DOT-CARE job on AHQ-AI-02 at 2025-04-30 17:19:49.

Error details:
create_json_payload() got an unexpected keyword argument 'source'

Traceback (most recent call last):
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\eligibilty_api_schedule.py", line 89, in _eligibility_iqama_job
    df_new["elgability_response"] = df_new.progress_apply(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\myenv\Lib\site-packages\tqdm\std.py", line 917, in inner
    return getattr(df, df_function)(wrapper, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\myenv\Lib\site-packages\pandas\core\frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\myenv\Lib\site-packages\pandas\core\apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\myenv\Lib\site-packages\pandas\core\apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\myenv\Lib\site-packages\pandas\core\apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\myenv\Lib\site-packages\tqdm\std.py", line 912, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\eligibilty_api_schedule.py", line 90, in <lambda>
    lambda row: send_json_to_api(create_json_payload(row, source=source)),
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_json_payload() got an unexpected keyword argument 'source'


Please check the scheduler.log file for more information.